### ISSUE TITLE
Launch tracking

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/phix#1]
Overall documentation for building an Exercism track lives at https://exercism.org/docs/building/tracks/new

This issue helps keep track of the tasks you're working on towards launching this track.

The next steps are:

- [x] [Join our community](https://exercism.org/docs/building/tracks/new/join-our-community)
- [x] [Select programming language variant](https://exercism.org/docs/building/tracks/new/select-programming-language-variant) (if applicable)
- [x] [Select testing framework](https://exercism.org/docs/building/tracks/new/select-testing-framework)
- [x] [Add the first exercise](https://exercism.org/docs/building/tracks/new/add-first-exercise)
- [x] [Add initial exercises](https://exercism.org/docs/building/tracks/new/add-initial-exercises)
- [x] [Setup Continuous Integration](https://exercism.org/docs/building/tracks/new/setup-continuous-integration)
- [x] [Prepare for launch](https://exercism.org/docs/building/tracks/new/prepare-for-launch)
- [ ] [Find Maintainers](https://exercism.org/docs/building/tracks/new/find-maintainers)
- [ ] [Launch!](https://exercism.org/docs/building/tracks/new/launch)
- [x] [Implement tooling](https://exercism.org/docs/building/tracks/new/implement-tooling)
- [ ] [Prepare for open source contributions from strangers](https://exercism.org/docs/building/tracks/new/prepare-for-contributions)

Once you've finished a task, you can check them in this list.

## Questions

Please ask if you have any questions or if anything is confusing!

**Comment by petelomax** [comment]
Where we at? (I'm about to pull this PC to bits and rebuild it, so might go dark for a couple of days, or more)

What needs to happen so that I can see how it will look?

**Comment by ErikSchierboom** [comment]
I don't have time right now to look into this. Maybe Tuesday or Wednesday.

**Comment by ErikSchierboom** [comment]
> What needs to happen so that I can see how it will look?

I've just added the track to the database. This means that it will be available to all maintainers to use, which we can use to test out the track. I would suggest writing a forum post asking people for help with testing out the track.

**Comment by petelomax** [comment]
Excellent, thanks. I've made a forum post. Some snag with the test runner, though it seemed OK on the CI side.
Should there be a separate phix-test-runner repo?
Should I be doing anything with that bot PR?

**Comment by kotp** [comment]
@ErikSchierboom requested [here] for the test runner repository, but likely need the other two as well, at some point:

- [x] [phix-analyzer]
- [x] [phix-representer]
- [x] [phix-test-runner]

[here]:  http://forum.exercism.org/t/phix-test-runner/12331
[phix-analyzer]: https://github.com/exercism/phix-analyzer
[phix-representer]: https://github.com/exercism/phix-representer
[phix-test-runner]: https://github.com/exercism/phix-test-runner

**Comment by ErikSchierboom** [comment]
Let me know when you need help

**Comment by kotp** [comment]
> Let me know when you need help

Request for `phix-test-runner` in the forum message linked in the above message.

**Comment by ErikSchierboom** [comment]
I've created all three repos.

**Comment by petelomax** [comment]
@ErikSchierboom Erm, how can I put this gently? Apart from nothing running and no syntax colouring, I am no more completely and utterly stumped on the Phix track than I have been for over a month.

**Comment by petelomax** [comment]
Cannot  commit or push anything - the button in GitHub Desktop is greyed out with no further clues. 
Do I need to be added as a maintainer?

**Comment by ErikSchierboom** [comment]
That is very weird. You're in the `phix` team and the `phix` team has write permissions on those repos.

**Comment by petelomax** [comment]
If I try and edit a file via (say) https://github.com/exercism/phix-test-runner/edit/main/bin/run.sh#L38C42 it says
You can’t commit to main because it is a protected branch.

https://github.com/exercism/phix-test-runner/rules/1297839 looks wrong to me, or at least there is no similar rule on the main phix repo

**Comment by ErikSchierboom** [comment]
> If I try and edit a file via (say) https://github.com/exercism/phix-test-runner/edit/main/bin/run.sh#L38C42 it says
You can’t commit to main because it is a protected branch.

That is because we don't want people directly committing to `main`, you'll need to use PRs.

**Comment by petelomax** [comment]
And I've just proved why that's a good idea (in my defence I was more concerned with getting github to obey me rather than what I was actually meant to be doing), PR created, and fixed on three counts.

**Comment by petelomax** [comment]
Any chance of any movement on this, anyone?
